(cl:defpackage hw4_service_rectangle_area-srv
  (:use )
  (:export
   "RECTANGLEAREASERVICE"
   "<RECTANGLEAREASERVICE-REQUEST>"
   "RECTANGLEAREASERVICE-REQUEST"
   "<RECTANGLEAREASERVICE-RESPONSE>"
   "RECTANGLEAREASERVICE-RESPONSE"
  ))

